services:
  xortp:
    image: anssi/fcsc2025-pwn-xortp:latest
    environment:
      - HOOS_CTF_EMAIL=${HOOS_CTF_EMAIL:-}
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
      - LANGUAGE=${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
    ports:
      - ${PORT}:4000
